--Part 1

--1

INSERT INTO item VALUES 
('30', 'Dell', 'Alienware 15', '2.1-GHz Intel Core i7-8750H processor, 16GB Memory, 256GB Solid State Drive');
INSERT INTO item VALUES 
('31', 'Apple', 'MacBook Air', '1.8GHz dual-core Intel Core i5 processor, 8GB of 1600MHz LPDDR3 onboard memory, 128GB PCIe-based SSD');
INSERT INTO item VALUES 
('32', 'HP', 'Envy', '8th Generation Intel Core i7 processor, 8 GB memory, 1 TB HDD');

--2
SELECT * FROM ITEM;

--3
ALTER TABLE LOAN
ADD CONSTRAINT RETURN_DAY_CONSTRAINT CHECK (DATE_RETURNED >= START_DATE);

--Part 2

--1
SELECT COMP_ID, COMP_NAME, ITEM_MANUF, ITEM_MODEL, SYSDATE - PURCHASE_DATE AS NUMBER_OF_DAYS_SINCE_PURCHASE 
FROM ITEM I JOIN COMPUTER C ON I.ITEM_ID = C.ITEM_ID
MINUS
SELECT C.COMP_ID, COMP_NAME, ITEM_MANUF, ITEM_MODEL, SYSDATE - PURCHASE_DATE AS NUMBER_OF_DAYS_SINCE_PURCHASE 
FROM ITEM I JOIN COMPUTER C ON I.ITEM_ID = C.ITEM_ID
JOIN LOAN L ON C.COMP_ID = L.COMP_ID;

--2 // NEED TO BE FIXED
SELECT DISTINCT S.ST_ID, ST_FNAME || ' ' || ST_LNAME AS NAME
FROM STUDENT S JOIN LOAN L ON S.ST_ID = L.ST_ID
JOIN COMPUTER C ON C.COMP_ID = L.COMP_ID
JOIN ITEM I ON I.ITEM_ID = C.ITEM_ID
WHERE ITEM_MANUF = 'Dell' AND  TO_CHAR(START_DATE,'YYYY') = TO_CHAR(SYSDATE,'YYYY')-1;

--3
SELECT S.ST_ID, ST_FNAME || ' ' || ST_LNAME AS NAME
FROM STUDENT S JOIN LOAN L ON S.ST_ID = L.ST_ID
JOIN COMPUTER C ON C.COMP_ID = L.COMP_ID
JOIN ITEM I ON I.ITEM_ID = C.ITEM_ID
WHERE ITEM_MANUF = 'Dell' OR ITEM_MANUF = 'HP'
MINUS
SELECT S.ST_ID, ST_FNAME || ' ' || ST_LNAME AS NAME
FROM STUDENT S JOIN LOAN L ON S.ST_ID = L.ST_ID
JOIN COMPUTER C ON C.COMP_ID = L.COMP_ID
JOIN ITEM I ON I.ITEM_ID = C.ITEM_ID
WHERE ITEM_MANUF != 'Dell' AND ITEM_MANUF != 'HP';

--4
SELECT COMP_NAME, ITEM_MODEL, L.LOCATION_ID || '- ' || LOC_BLDG || ',' || LOC_ROOM AS LOCATION
FROM COMPUTER C JOIN ITEM I ON I.ITEM_ID = C.ITEM_ID
JOIN LOCATION L ON C.LOCATION_ID = L.LOCATION_ID
JOIN LOAN LO ON LO.COMP_ID = C.COMP_ID
WHERE ITEM_MANUF = 'Dell' AND (START_DATE >= '01-JAN-17' AND START_DATE <= '31-DEC-17') AND (DATE_RETURNED >= '01-JAN-17' AND DATE_RETURNED <= '31-DEC-17');

--5
SELECT ITEM_MODEL
FROM ITEM I JOIN COMPUTER C ON I.ITEM_ID = C.ITEM_ID
JOIN LOAN L ON L.COMP_ID = C.COMP_ID
JOIN STUDENT S ON S.ST_ID = L.ST_ID
JOIN LOCATION LOC ON LOC.LOCATION_ID = C.LOCATION_ID
WHERE LOC_BLDG = 'HBH' AND ST_FNAME = 'Fred' AND ST_LNAME = 'Couples'
MINUS
SELECT ITEM_MODEL
FROM ITEM I JOIN COMPUTER C ON I.ITEM_ID = C.ITEM_ID
JOIN LOAN L ON L.COMP_ID = C.COMP_ID
JOIN STUDENT S ON S.ST_ID = L.ST_ID
JOIN LOCATION LOC ON LOC.LOCATION_ID = C.LOCATION_ID
WHERE LOC_BLDG = 'HBH'AND ST_FNAME = 'Joan' AND ST_LNAME = 'Nimoy';

--6
SELECT ST_ID || ' - ' || ST_FNAME || ' ' || ST_LNAME AS STUDENT_NAME, EMAIL
FROM STUDENT
MINUS
SELECT S.ST_ID || ' - ' || ST_FNAME || ' ' || ST_LNAME AS STUDENT_NAME, EMAIL
FROM STUDENT S JOIN LOAN L ON S.ST_ID = L.ST_ID;




